version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://mina:0000@192.168.211.128:5432/mydb

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: mina
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: mydb
